name: Capstone CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache front-end node modules
        id: front-end-node-cache
        uses: actions/cache@v2
        with:
          path: front-end/node_modules
          key: ${{ runner.os }}-front-end-${{ hashFiles('front-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-front-end-

      - name: npm install in front-end
        if: steps.front-end-node-cache.outputs.cache-hit != 'true'
        run: cd front-end && npm install

      - name: Build front-end
        run: cd front-end && npm run build --if-present

      - name: Test front-end
        run: cd front-end && npm test
        env:
          DATABASE_URL_TEST: postgresql://postgres:postgres@127.0.0.1:5432
          NODE_ENV: test

      - name: Archive front-end screenshots
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: front-end/.screenshots

      - name: Cache back-end node modules
        id: back-end-node-cache
        uses: actions/cache@v2
        with:
          path: back-end/node_modules
          key: ${{ runner.os }}-back-end-${{ hashFiles('back-end/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-back-end-

      - name: npm install in back-end
        if: steps.back-end-node-cache.outputs.cache-hit != 'true'
        run: cd back-end && npm install

      - name: Test back-end
        run: cd back-end && npm test
        env:
          DATABASE_URL_TEST: postgresql://postgres:postgres@127.0.0.1:5432
          NODE_ENV: test
